### ISSUE TITLE
looks like kali-rolling-cli-armhf is missing

### ISSUE THREAD

**Issue by imbeee** [GoVanguard/karmbian#10]
[ o.k. ] Starting rootfs and image building process for [ orangepizero kali-rolling ]
[ o.k. ] Checking for local cache [ kali-rolling-cli-armhf.3b5...8d0.tar.lz4 ]
[ .... ] searching on servers
Exception caught
Exception: [download_helper.cc:451] errorCode=1 Unrecognized URI or unsupported protocol:

[ warn ] Failed to download control file
[ .... ] downloading using torrent network [ kali-rolling-cli-armhf.3b54444176d49ebe2d1437a7714be8d0.tar.lz4 ]
[#f8dda4 0B/0B CN:1 DL:0B]
11/25 17:34:17 [ERROR] CUID#6 - Download aborted. URI=https://dl.armbian.com/torrent/kali-rolling-cli-armhf.3b54444176d49ebe2d1437a7714be8d0.tar.lz4.torrent
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://uk.mirrors.fossho.st/armbian/dl/torrent/kali-rolling-cli-armhf.3b54444176d49ebe2d1437a7714be8d0.tar.lz4.torrent
  -> [HttpSkipResponseCommand.cc:219] errorCode=3 Resource not found

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
[ .... ] not found: try to use previous cache
[ o.k. ] Checking for local cache [ kali-rolling-cli-armhf.33f...288.tar.lz4 ]
[ .... ] searching on servers
[ .... ] not found: try to use previous cache
[ o.k. ] ... remote not found [ Creating new rootfs cache for kali-rolling ]
[ o.k. ] Installing base system [ Stage 1/2 ]
E: No such script: /usr/share/debootstrap/scripts/kali-rolling
[ error ] ERROR in function create_rootfs_cache [ debootstrap.sh:164 ]
[ error ] Debootstrap base system first stage failed
[ o.k. ] Process terminated
[ o.k. ] Unmounting [ /home/ubuntu/karmbian/.tmp/rootfs-current-orangepizero-kali-rolling-no-no/ ]
[ error ] ERROR in function unmount_on_exit [ image-helpers.sh:66 ]
[ error ] debootstrap-ng was interrupted
[ o.k. ] Process terminated

**Comment by EvilOlaf** [comment]
Maybe Karmbian should setup own torrent mirrors :P

**Comment by imbeee** [comment]
> Maybe Karmbian should setup own torrent mirrors :P

yeah, but I think this project will likely not update anymore. lol

**Comment by sscottgvit** [comment]
We're working on setting up our own infrastructure. Fairly soon we'll strip out these external dependancies.

**Comment by imbeee** [comment]
> We're working on setting up our own infrastructure. Fairly soon we'll strip out these external dependancies.

Great. Before that I figured out a way to create the kali rootfs myself and it seems works.
BTW, after buinding the image, I take a look at the build scripts, it looks like we are building the kernel from armbian, not from kali. As we know, some wireless nic drivers from kali had been modified for the packets injection feature. Is karmbian working well with these features?

**Comment by imbeee** [comment]
Hi all, here is my workaround:

**Make sure you apply this patch**
[https://github.com/GoVanguard/karmbian/pull/7/commits/07dc00eb2e355e6c0a4e6a621077d099c34234a6](url)

**You can always disable bt download using `export USE_TORRENT=no` if you are under a strict network environment.**

a) If you are using the correct version of kali as host system, it should be fine when you set ROOT_FS_CREATE_ONLY to FORCE before building using `export ROOT_FS_CREATE_ONLY=FORCE`, the scripts will create a rootfs from debootstrap rather than using the prebuild version from armbian. But sometimes it failed when installing packages because some dependency problems on the kali host.

b) You can use the function `create_rootfs_cache` from `karmbian/lib/debootstrap.sh` to create the rootfs on a kali host, then put it to `karmbian/cache/rootfs` and use it to build the image on a ubuntu host. Download my prebuild rootfs: [https://drive.google.com/drive/folders/1_4zEPTpVS-h9Aywi-QDkBadOOcC5dop3?usp=sharing](url)
